# about dataset
train_csv_file: ./csv/train.csv

input_size: 64
batch_size: 16

# training hyper parameters
z_dim: 20
channel: 1
ngf: 64 # same as the input_size
ndf: 64 # same as the input_size
extralayer: 0

num_epochs: 300
num_fakeimage: 5

# training output
save_dir: ./weights

# wandb
name: mnist78-2020-02-12